import = ["/home/eloi/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/bash"

[window]
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"
