require("default.plugin.barbar")
require("default.plugin.colors")
-- require("default.plugin.comment")
require("default.plugin.gitblame")
require("default.plugin.gitsigns")
require("default.plugin.indent-blankline")
require("default.plugin.lualine")
require("default.plugin.live-preview")
-- require("default.plugin.neorg")
require("default.plugin.nvim-tree")
require("default.plugin.telescope")
require("default.plugin.treesitter")
require("default.plugin.lsp")
require("default.plugin.blink")

-- Remove all inactive plugins
local inactive_plugins = vim.iter(vim.pack.get())
    :filter(function(x) return not x.active end)
    :map(function(x) return x.spec.name end)
    :totable()
vim.pack.del(inactive_plugins)
