require("default.plugin.barbar")
require("default.plugin.colors")
require("default.plugin.gitblame")
require("default.plugin.gitsigns")
require("default.plugin.indent-blankline")
require("default.plugin.lualine")
require("default.plugin.mason")
-- require("default.plugin.neorg")
require("default.plugin.telescope")
require("default.plugin.treesitter")
require("default.plugin.nvim-tree")
require("default.plugin.comment")
