-- set leader BEFORE setting up anything else
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

-- ({
--     -- Hot new chick in town
--     { 'saghen/blink.cmp' },
--     -- -- OG
-- 	-- {'hrsh7th/nvim-cmp'},
--
-- 	-- The Foking LSP
-- 	-- {
-- 	-- 	'VonHeikemen/lsp-zero.nvim',
-- 	-- 	branch = 'v1.x',
-- 	-- 	dependencies = {
-- 	-- 		-- LSP Support
-- 	-- 		{'neovim/nvim-lspconfig'},             -- Required
-- 	-- 		{'williamboman/mason.nvim'},           -- Optional
-- 	-- 		{'williamboman/mason-lspconfig.nvim'}, -- Optional
-- 	--
-- 	-- 		-- Autocompletion
-- 	-- 		{'hrsh7th/cmp-nvim-lsp'},     -- Required
-- 	-- 		{'hrsh7th/cmp-buffer'},       -- Optional
-- 	-- 		{'hrsh7th/cmp-path'},         -- Optional
-- 	-- 		{'saadparwaiz1/cmp_luasnip'}, -- Optional
-- 	-- 		{'hrsh7th/cmp-nvim-lua'},     -- Optional
-- 	--
-- 	-- 		-- Snippets
-- 	-- 		{'L3MON4D3/LuaSnip'},             -- Required
-- 	-- 		{'rafamadriz/friendly-snippets'}, -- Optional
-- 	-- 	}
-- 	--
-- 	-- },
--
-- 	-- Trailing spaces
-- 	{"ntpeters/vim-better-whitespace"},
--
--
--
--     -- DiffView plugin
--     {"sindrets/diffview.nvim"},
--
--     {
--         "hedyhli/outline.nvim",
--         config = function()
--             -- Example mapping to toggle outline
--             vim.keymap.set("n", "<leader>o", "<cmd>Outline<CR>",
--             { desc = "Toggle Outline" })
--
--             require("outline").setup {
--                 -- Your setup opts here (leave empty to use defaults)
--             }
--         end,
--     },
--
--     {
--         "nvim-neorg/neorg",
--         lazy = false,
--         version = "*",
--         config = function()
--             require("neorg").setup {
--                 load = {
--                     ["core.defaults"] = {},
--                     ["core.concealer"] = {},
--                     ["core.dirman"] = {
--                         config = {
--                             workspaces = {
--                                 neorg = "~/neorg",
--                             },
--                             default_workspace = "neorg",
--                         },
--                     },
--                 },
--             }
--             vim.wo.foldlevel = 99
--             vim.wo.conceallevel = 2
--         end,
--     },
--
-- }, opts);

require("default")
